version: "3"
services:
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  customerService:
    build:
      dockerfile: Dockerfile
      context: .
    image: workshop3:1.0
    # ports:
    #   - "3000:3000"
    environment:
      - CUSTOMER_SVC_PORT=3000
      - CUSTOMER_DB_URL=mongodb://localhost:27017/customer-db
    links:
      - mongo
